<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Mon, 24 Jul 2017 11:32:45 +0800
 */

$conf['title'] = 'PHP Wiki';
$conf['template'] = 'phpnet';
$conf['fmode'] = 0777;
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['usewordblock'] = 0;
$conf['subscribers'] = 1;
$conf['registernotify'] = 'ihotte@yeah.net';
$conf['mailfrom'] = 'ihotte@yeah.net';
$conf['rss_content'] = 'htmldiff';
$conf['updatecheck'] = 0;
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['send404'] = 1;
$conf['dnslookups'] = 0;
$conf['proxy']['host'] = '127.0.0.1';
$conf['proxy']['port'] = 1080;

// end auto-generated content
